### ISSUE TITLE
Zero-Rating

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#18] opened 2015-08-26 10:55 UTC
- Faciliators name
-  A discussion about what zero rating is, how it's impacting people in different parts of the world and sharing research that has been done around the subject.

**Comment by Melechuga** [comment] 2015-09-15 22:06
Duplicate of https://github.com/mozilla/mozfest-program/issues/196

**Closed as completed by Melechuga** 2015-09-15 22:06 UTC
