### ISSUE TITLE
Run the Gauntlet

### ISSUE THREAD

**Issue by Saallen** [mozilla/mozfest-program#30] opened 2015-09-03 13:38 UTC
- Su Adams
- "This session is aimed at creatively engaging children to use a variety of talents towards a common goal.  Children will add to an activity course for the Sphero or Arduino robot, to create a colourful, interactive end result by the end of the weekend.
  Example:
  A child (or adult) might decide to make a tunnel or see-saw bridge etc... to add to the course then attach a MakeyMakey or Arduino and program it using Scratch, S4A or Mind+ etc... to code a response to an input for example a noise of some sort or traffic lights to change at another section.  
  - The aim is to demonstrate how many skills come together to create a great end result and to realise how all skills are valuable.  i.e. a child may choose to create and decorate a tunnel without any coding.
    Drop in and/or session based, individuals can turn up and use the resources (cardboard boxes, paper, plastic containers etc...), electronics and programmable boards, along with their imagination to expand on a small pre-existing course. There will be a starting point already created by the Digital Leaders and Code Clubbers of our school.  This will provide ideas and something interesting to begin with.We will have some Arduino's and MakeyMakey's, possibly a couple of Pi's too, but any additions would be helpful is that is possible.  We will bring laptops for the programming aspects.
    The session would run over the whole weekend and be manned by the Digital Leaders, Code Clubbers, Website Club and Weaving the Web (web literacy club) Members of our school supported by myself and enough Adults to appropriately support the children."

**Comment by Melechuga** [comment] 2015-09-15 22:14
Duplicate of https://github.com/mozilla/mozfest-program/issues/52

**Comment by thornet** [comment] 2015-09-16 15:26
thanks @Melechuga and @mixedpuppy for closing all the duplicates.

**Closed as completed** 2015-10-12 10:31 UTC
