### ISSUE TITLE
Putting users in charge: Introduction to the browser privacy UI

### ISSUE THREAD

**Issue by mmmavis** [mozilla/mozfest-program#221] opened 2015-09-10 18:15 UTC
**[ Google Spreadsheet Row Number ]** 194
**[ Facilitator ]**

name: Lukasz Olejnik
twitter: @lukOlejnik
organization: 
### Description

Privacy issue often result just due to how technology is architected! We address the latest issues in browser privacy and transparency mechanisms. Want to hear about the current browser developments and the possible privacy risks and walk away equipped with a privacy-sensitive mindset and concepts? Are we satisfied with how browsers work? Do we know what data are provided to Web sites by our browsers? We will discuss if - and how to possibly improve the user interfaces.

**Comment by Melechuga** [comment] 2015-09-16 00:56
Applied with my prodding; would be coming from Ireland.

**Comment by Melechuga** [comment] 2015-09-21 21:46
Possible collaboration with https://github.com/mozilla/mozfest-program/issues/169

**Comment by lknik** [comment] 2015-11-02 17:10
Hi,

I would like to share an outline/plan. It was intended for myself but perhaps participants might find it useful. Of course, nothing there is fixed in stone.

https://github.com/lknik/documents/blob/master/mozfest.pdf

**Comment by Melechuga** [comment] 2015-11-02 17:26
Hi @lknik The top-line information here (facilitator name, session description, etc) has been pulled into a scheduling application. I suggest you bring print-outs of your document to your session.

**Closed as completed** 2024-07-23 12:45 UTC
Labels: Backdoors + Cryptowars, [DC] Accepted, ARCHIVED - http://mzl.la/ghe-archive
